### ISSUE TITLE
Newly created sessions aren't deleted if nobody actually joins them.

### ISSUE THREAD

**Issue by LBBO** [LBBO/stream-together#14]
If somebody makes a request to `/createSession` but then doesn't join the newly created session, said session is never deleted. This is because the check for emptiness currently only takes place when a user leaves a session.

There should either be a regular check for all (or only newly created) sessions that removes them if empty, or session creation should be moved to when it is actually joined. It might make most sense to just add a timeout to every new session that deletes it again if nobody joins within something like a minute. That way, the interval is always the same for each session.

**Comment by s-gbz** [comment]
Going to take a look at it! Feel free to assign me.
