### ISSUE TITLE
Create an icon for the plugin

### ISSUE THREAD

**Issue by LBBO** [LBBO/stream-together#23]
The Chrome Web Store requires each and every plugin to have an icon with 128 x 128 pixels. Ideally, this icon would also be recognizable when down-scaled to 48 x 48 or even 16 x 16 pixels in order to double as a favicon.

Other than that, I have no requirements. Be creative!

For more details, please see [Chrome's documentation on extension icons](https://developer.chrome.com/extensions/manifest/icons)

**Comment by CrazyTranslator** [comment]
It's my first time on hacktober, I have an icon for you, saved both as png and svg, do I need to clone your project and make a pull request or do I send it here as a comment?
